ALTER TABLE users ADD COLUMN header_image_url VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN bio TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN location VARCHAR(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN website VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(255) DEFAULT NULL;
